default_platform(:android)

platform :android do
  desc "Upload store listing metadata and graphics to Google Play"
  lane :metadata do
    upload_to_play_store(
      track: "internal",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: false,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: true,
      metadata_path: "fastlane/metadata/android"
    )
  end

  desc "Promote internal track to production"
  lane :promote do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: false,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: true
    )
  end
end
